# -*- coding: utf-8 -*-
"""KP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RR0eLhaBU9xKLDl7SCr6gK0s_gNtq1-j
"""

!pip install langchain
!pip install openai
!pip install PyPDF2
!pip install faiss-cpu
!pip install tiktoken

from PyPDF2 import PdfReader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import ElasticVectorSearch, Pinecone, Weaviate, FAISS

import os
os.environ["OPENAI_API_KEY"] = "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"

reader = PdfReader('/content/AUTENTIFIKASI PERWAL 044 TAHUN 2019-1-10.pdf')

reader

raw_text =''
for i, page in enumerate(reader.pages):
    text = page.extract_text()
    if text:
        raw_text += text

raw_text

raw_text[:100]

text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 1000,
    chunk_overlap  = 200,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)

len(texts)

texts[0]

texts[1]

embeddings = OpenAIEmbeddings()

docsearch = FAISS.from_texts(texts, embeddings)

docsearch

from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI

chain = load_qa_chain(OpenAI(), chain_type="stuff")

query = "usia paling tinggi berapa tahun?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "Undang-Undang Nomor 30 Tahun 2014 tentang apa?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "Peraturan Kepala Badan Kepegawaian Negara Nomor 18 Tahun 2006 tentang apa?"
docs = docsearch.similarity_search(query)
chain.run(input_documents=docs, question=query)

